[package]
name = "WebSearch_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.15", features = ["blocking"] }
scraper = "0.23.1"
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
chrono = "0.4.40"